[?1034h$ cd 
$ cd swc/ou_swc_files/
$ ls
[34mUsers[39;49m[0m        [34mgapminder[39;49m[0m    [34minflammation[39;49m[0m [34mr-gapminder[39;49m[0m
$ pwd 
/Users/laufers/swc/ou_swc_files
$ cd Users/
$ ls
[34mimhotep[39;49m[0m [34mlarry[39;49m[0m   [34mnelle[39;49m[0m
$ cd nelle
$ ls
[34mDesktop[39;49m[0m            [34mdata[39;49m[0m               [34mnorth-pacific-gyre[39;49m[0m pizza.cfg          [34mwriting[39;49m[0m
[34mcreatures[39;49m[0m          [34mmolecules[39;49m[0m          notes.txt          solar.pdf
$ pwd 
/Users/laufers/swc/ou_swc_files/Users/nelle
$ cd cra[Keaters[K[K[Kures
$ pwd 
/Users/laufers/swc/ou_swc_files/Users/nelle/creatures
$ ls
basilisk.dat unicorn.dat
$ Ech[K[K[Kecho "this is very[K[K[K[Kinteresting and seems to s[Kwork pretty nice. I [K[K[K"
this is interesting and seems to work pretty nice.
$ echo I [K[K" I[K[KI am looking fow[Krward to hearing how this woe[Krked in the last OSU SWC workshop."
I am looking forward to hearing how this worked in the last OSU SWC workshop.
$ ls
basilisk.dat unicorn.dat
$ pwd 
/Users/laufers/swc/ou_swc_files/Users/nelle/creatures
$ cd ../
$ ls
[34mDesktop[39;49m[0m            [34mdata[39;49m[0m               [34mnorth-pacific-gyre[39;49m[0m pizza.cfg          [34mwriting[39;49m[0m
[34mcreatures[39;49m[0m          [34mmolecules[39;49m[0m          notes.txt          solar.pdf
$ cd north-pacific-gyre/
$ ls
[34m2012-07-03[39;49m[0m
$ cd 20qe[K[K12-07-03
$ ls
NENE01729A.txt NENE01751B.txt NENE01971Z.txt NENE02040A.txt NENE02043B.txt
NENE01729B.txt NENE01812A.txt NENE01978A.txt NENE02040B.txt goodiff
NENE01736A.txt NENE01843A.txt NENE01978B.txt NENE02040Z.txt goostats
NENE01751A.txt NENE01843B.txt NENE02018B.txt NENE02043A.txt
$ ls *[AB].txt
NENE01729A.txt NENE01751A.txt NENE01843A.txt NENE01978B.txt NENE02040B.txt
NENE01729B.txt NENE01751B.txt NENE01843B.txt NENE02018B.txt NENE02043A.txt
NENE01736A.txt NENE01812A.txt NENE01978A.txt NENE02040A.txt NENE02043B.txt
$ ls *[AB].txt | wo[Kc -l 
      15
$ ls *.txt | wc -l
      17
$ for fiel[K[Klename in *.txt
> do
> echo '[K$filename
> wc -l $filename
> echo ''
> done 
NENE01729A.txt
     300 NENE01729A.txt

NENE01729B.txt
     300 NENE01729B.txt

NENE01736A.txt
     300 NENE01736A.txt

NENE01751A.txt
     300 NENE01751A.txt

NENE01751B.txt
     300 NENE01751B.txt

NENE01812A.txt
     300 NENE01812A.txt

NENE01843A.txt
     300 NENE01843A.txt

NENE01843B.txt
     300 NENE01843B.txt

NENE01971Z.txt
     300 NENE01971Z.txt

NENE01978A.txt
     300 NENE01978A.txt

NENE01978B.txt
     300 NENE01978B.txt

NENE02018B.txt
     240 NENE02018B.txt

NENE02040A.txt
     300 NENE02040A.txt

NENE02040B.txt
     300 NENE02040B.txt

NENE02040Z.txt
     300 NENE02040Z.txt

NENE02043A.txt
     300 NENE02043A.txt

NENE02043B.txt
     300 NENE02043B.txt

$ for filename in *.txt; do echo $filename; wc -l $filename; echo ''; done [1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P[1P
     300 NENE01729A.txt
     300 NENE01729B.txt
     300 NENE01736A.txt
     300 NENE01751A.txt
     300 NENE01751B.txt
     300 NENE01812A.txt
     300 NENE01843A.txt
     300 NENE01843B.txt
     300 NENE01971Z.txt
     300 NENE01978A.txt
     300 NENE01978B.txt
     240 NENE02018B.txt
     300 NENE02040A.txt
     300 NENE02040B.txt
     300 NENE02040Z.txt
     300 NENE02043A.txt
     300 NENE02043B.txt
$ exit
[?1034h$ ls
[31mansi2html.sh[39;49m[0m         [33mfull_terminal.pipe[39;49m[0m   readme.md            transcript.bashrc
[31mauto_push.sh[39;49m[0m         full_terminal.script setup_ssh_key.sh
commands.txt         index.html           short_prompt.bashrc
full_terminal.html   make_html.sh         start_transcript.sh
$ git stuat[K[K[Katus
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	[31mmodified:   full_terminal.script[m

no changes added to commit (use "git add" and/or "git commit -a")
$ git add fi[Kull_terminal.script 
$ git commands.txt [K[K[K[K[K[K[K[K[K[K[K[Kommit -m 'test;[K'
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
	[31mmodified:   full_terminal.script[m

no changes added to commit
$ git stauts[K[K[Ktus
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	[31mmodified:   commands.txt[m
	[31mmodified:   full_terminal.script[m

no changes added to commit (use "git add" and/or "git commit -a")
$ 